services:
  dathost-bridge:
    build:
      context: ..
      dockerfile: bridge/Dockerfile.prebuilt

  mc-relay:
    build:
      context: ..
      dockerfile: relay/Dockerfile.prebuilt

  discord-commands:
    build:
      context: ..
      dockerfile: discord-commands/Dockerfile.prebuilt

  kanban-sync:
    build:
      context: ..
      dockerfile: kanban-sync/Dockerfile.prebuilt

  inventory-sync:
    build:
      context: ..
      dockerfile: inventory-sync/Dockerfile.prebuilt
