services:
  mc-relay:
    build:
      context: ..
      dockerfile: relay/Dockerfile.prebuilt

  discord-commands:
    build:
      context: ..
      dockerfile: discord-commands/Dockerfile.prebuilt

  inventory-sync:
    build:
      context: ..
      dockerfile: inventory-sync/Dockerfile.prebuilt
