modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
Client-side utility mod that dumps live FTB Quests completion state to JSON files.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "ftbquests"
type = "required"
versionRange = "[2101.1.22,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "ftbteams"
type = "required"
versionRange = "[2101.1.9,)"
ordering = "AFTER"
side = "CLIENT"
