plugins {
  id 'java-library'
  id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

base {
  archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

def prismRoot =
    System.getenv('PRISM_ROOT')
        ?: "${System.properties['user.home']}/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher"

sourceSets {
  main {
    java {
      srcDirs = ['../../scripts/ftbquests_dump']
    }
    resources {
      srcDirs = ['../../scripts/ftbquests_dump']
      include 'META-INF/**'
    }
  }
}

repositories {
  mavenCentral()
}

dependencies {
}

neoForge {
  version = project.neo_version

  mods {
    "${mod_id}" {
      sourceSet(sourceSets.main)
    }
  }
}

tasks.withType(ProcessResources).configureEach {
  def replaceProperties = [
    minecraft_version: minecraft_version,
    minecraft_version_range: minecraft_version_range,
    neo_version: neo_version,
    neo_version_range: neo_version_range,
    loader_version_range: loader_version_range,
    mod_id: mod_id,
    mod_name: mod_name,
    mod_license: mod_license,
    mod_version: mod_version,
  ]
  inputs.properties replaceProperties
  filesMatching(['META-INF/neoforge.mods.toml']) {
    expand replaceProperties
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}
